### ISSUE TITLE
Call to undefined function system_date_format_locale()...

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/date#7]
Got this message when trying to save a node with a Date field.

**Comment by ghost** [comment]
Looks like you just need to change

``` php
$format = system_date_format_locale($langcode, $format_type);
```

in `date_formatter_format()` to

``` php
$date_format = system_date_format_load($format_type);
$format = isset($date_format['locales'][$langcode]) ? $date_format['locales'][$langcode] : $date_format['pattern'];
```

as per https://api.backdropcms.org/node/41663

**Comment by Graham-72** [comment]
Included in commit https://github.com/backdrop-contrib/date/commit/42100ca0e742e91c40417588c2708707c171ad44

**Comment by ghost** [comment]
Nice, thanks.
